{% set version = "0.21" %}
{% set sha256 = "924f8e2b4e3cb3d8b26246b5f9c07cdaa4b8800cef345fa0811d72930d73a54e" %}

package:
  name: perl-carp-assert
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/N/NE/NEILB/Carp-Assert-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win]
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test
    - make install VERBINST=1

requirements:
  build:
    - make
  host:
    - perl
  run:
    - perl

test:
  imports:
    - Carp::Assert

about:
  home: http://metacpan.org/pod/Carp::Assert
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  summary: 'Executable comments'

extra:
  recipe-maintainers:
    - micknudsen
