travis:
  secure:
    BINSTAR_TOKEN: NL4/8Aw6k+uSzYMshYBGxBdxUiiwLg+5t0EAFVQO6PMZfq7rZAuznwhj0JlxHZeRU+sqxbpyycvJdXDyrvQhYvT05m1nU9R8giqcz5p5/7v0vKOG4wxY6YdgMgBuvyrj+gqTw9sjqoJZSbso47FX1AdSHrq5kaG8k5HOmmUSG1nUknox7OURuhPegOTlqY34fMCGadpwFDSa+GgqSOwtGmFBGufne0zkEv2CDkDeWHyYy2bjLnZsCfGjGnVOZKNkwzw8T9W89mA1/S87nBJR4fFLoRSzLyqasqWI+QbkrDL54DMUQB2HVei1p0hKO79WutspCcyyr+OUEVP4D+oIzCqPlEgPJeAHkudvWAIdycxYsZm9Md6gUOz3GaowSaJqpaYjYcIAFVMnpbpYN5veVWppir5dTsdVFwergAVc+fKCaZAunUXE8o3XmuYWwxv6Gf8Bih1AV+F2+mXbWFLiA+RhGentqM6Cg8O51X2nIP+wMkbHTjOAkOWAqbY86evSYwvrdShknor+ztoLtiJB+BkwZhXfKQ/xAaPPHHDRrZEqljRKxt8KJ0rt643S1LAXlTAYbFtlqcZOFqMWMLBiPb4+X9gJTJqcKfqgh2CSH1Z7XqRzvkCv0na59TqIbDg3xlNIdDu046fWgFoZfHf7swvBoNsuLNUMXbKdo+zsMOE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
